apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo-svc
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-container
          image: mongo
          command:
            - mongod
          args:
            - --bind_ip=0.0.0.0
            - --replSet=rs0
            - --dbpath=/data/db
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: db-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi