apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: web
    name: mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      name: mongo-express
  template:
    metadata:
      labels:
        app: web
        name: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54.0
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb://mongo-0.mongo-svc.default,mongo-1.mongo-svc.default,mongo-2.mongo-svc.default?replicaSet=ns0
        ports:
          - containerPort: 8081