apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-server
  name: nginx-server-v1
spec:
  containers:
  - image: nginx:1.19.4-alpine
    name: nginx-server
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never