apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-server
  labels:
    app: nginx-server-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - image: nginx:1.19.4-alpine
        name: nginx-server
        resources:
          limits:
            cpu: 20m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 128Mi
        ports:
        - containerPort: 80