apiVersion: v1
kind: Service
metadata:
  name: nginx-server-svc3
spec:
  type: NodePort
  selector:
    app: nginx-server
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 80
    nodePort: 30007