apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-server
  labels:
    app: nginx-server
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - image: nginx:1.19.4-alpine
        name: nginx-server